//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by TABLEGEN.RC
//
#define IDR_MAINFRAME                   1
#define IDR_APPICON                     2
#define IDR_BLUEGERANIUM                3
#define IDR_GERANIUM_BANNER             4
#define IDD_PAGE0                       11
#define IDD_PAGE1                       12
#define IDD_PAGE2                       13
#define IDD_PAGE3                       14
#define IDD_PAGE4                       15
#define IDD_PAGE5                       16
#define IDS_LOAD_BITMAP                 101
#define IDS_LOAD_BITMAP_FILES_DEFAULT   102
#define IDS_LOAD_BINARY                 103
#define IDS_LOAD_BITMAP_FILES_LABLE     104
#define IDS_LOAD_BITMAP_FILES_OK_BUTTON 105
#define IDS_LOAD_BINARY_FILE_DEFAULT    106
#define IDS_LOAD_BINARY_FILE_LABLE      107
#define IDS_LOAD_BINARY_FILE_OK_BUTTON  108
#define IDS_SELECT_OUTPUT_FOLDER        200
#define IDS_SELECT_OUTPUT_FOLDER_DEFAULT 201
#define IDS_SELECT_OUTPUT_FOLDER_LABLE  202
#define IDS_SELECT_OUTPUT_FOLDER_OK_BUTTON 203
#define IDS_LOAD_LIST_FILE              320
#define IDS_LOAD_LIST_FILE_DEFAULT      321
#define IDS_LOAD_LIST_FILE_FILENAME_LABLE 322
#define IDS_LOAD_LIST_FILE_OK_BUTTON    323
#define IDS_SAVE_LIST_FILE_ASM          440
#define IDS_SAVE_LIST_FILE_DEFAULT_ASM  441
#define IDS_SAVE_LIST_FILE_FILENAME_LABLE 442
#define IDS_SAVE_LIST_FILE_OK_BUTTON    443
#define IDS_SAVE_LIST_FILE_DEFAULT_BIN  444
#define IDS_SAVE_LIST_FILE_BIN          445
#define IDS_SAVE_LIST_FILE_VERILOG      446
#define IDS_SAVE_LIST_FILE_DEFAULT_VERILOG 447
#define IDS_GERANIUM_CONVERT_MESSAGE    500
#define IDS_GERANIUM_CONVERT_MESSAGE_1  501
#define IDS_WINDOW_TITLE_0              600
#define IDS_WINDOW_TITLE_1              601
#define IDS_WINDOW_TITLE_2              602
#define IDS_WINDOW_TITLE_3              603
#define IDS_WINDOW_TITLE_4              604
#define IDS_WINDOW_TITLE_5              605
#define IDS_TEXT_VERILOG_BUTTON         700
#define IDS_TEXT_BINARY_BUTTON          701
#define IDS_TEXT_LIST_BOX_BITMAP_IMAGE  702
#define IDS_TEXT_LIST_BOX_SIN_WAVE      703
#define IDS_TEXT_LIST_BOX_BITMAP_TESTER 704
#define IDS_TEXT_LIST_BOX_LOOK_UP_TABLE 705
#define IDS_TEXT_LIST_BOX_ASCII_TEXT_CONVERSION 706
#define IDS_TEXT_LIST_BOX_VERILOG_ROM   707
#define IDS_TEXT_WORDSIZE_BUTTON        708
#define IDS_TEXT_WORDSIZE_BUTTON2       709
#define IDS_TEXT_ENDIAN_BUTTON          709
#define IDC_EDIT_A                      1004
#define IDC_EDIT_B                      1005
#define IDC_COMBO_TABLE_TYPE            1005
#define IDC_EDIT_C                      1006
#define IDC_BUTTON_FILE_SELECT          1006
#define IDC_EDIT_D                      1007
#define IDC_STATIC_UNKNOWN_TYPE         1007
#define IDC_EDIT_FILE_NAME_OUTPUT       1008
#define IDC_STATIC_BOX_A_TEXT           1009
#define IDC_STATIC_BOX_B_TEXT           1010
#define IDC_STATIC_BOX_C_TEXT           1011
#define IDC_STATIC_BOX_D_TEXT           1012
#define IDC_BUTTON_A                    1013
#define IDC_BUTTON_B                    1014
#define IDC_STATIC_PICTURE              1014
#define IDC_BUTTON_C                    1015
#define IDC_BUTTON_LEFT                 1015
#define IDC_BUTTON_D                    1016
#define IDC_BUTTON_RIGHT                1016
#define IDC_EDIT_TOTAL_ENTRIES          1016
#define IDC_STATIC_TOTAL_ENTRIES        1017
#define IDC_EDIT_START_VALUE            1018
#define IDC_EDIT_TEXT_INPUT             1018
#define IDC_STATIC_START_VALUE          1019
#define IDC_EDIT_CHARACTERS_PER_LINE    1019
#define IDC_EDIT_END_VALUE              1020
#define IDC_STATIC_CHARACTERS_PER_LINE_TEXT 1020
#define IDC_STATIC_END_VALUE            1021
#define IDC_BINARY_CHECK                1021
#define IDC_EDIT_INCREMENT              1022
#define IDC_VERILOG_CHECK               1022
#define IDC_STATIC_INCREMENT            1023
#define IDC_WORDSIZE_CHECK              1023
#define IDC_ENDIAN_CHECK                1024
#define IDC_LBL_TITLE                   3000
#define IDC_LBL_WELCOME                 3001
#define IDS_ASM_FILE_FILTERS            4000
#define IDS_LOAD_BITMAP_FILES_FILTERS   4001
#define IDS_BIN_FILE_FILTERS            4002
#define IDS_VERILOG_FILE_FILTERS        4003
#define IDS_LIST_FILE_FILTERS           4004

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        20001
#define _APS_NEXT_COMMAND_VALUE         32767
#define _APS_NEXT_CONTROL_VALUE         1022
#define _APS_NEXT_SYMED_VALUE           20101
#endif
#endif
